lythosJSF2/lythosJSF2-war/src/java/modeloTerminalMovil/AdminModeloMovilBean.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package modeloTerminalMovil;

import dao.ModelomovilFacade;
import entidades.Modelomovil;
import java.io.IOException;
import java.util.List;
import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ApplicationScoped;
import javax.faces.context.FacesContext;

/**
 *
 * @author IsmiKinPorti
 */
@ManagedBean(name = "administracionModelos")
@ApplicationScoped
public class AdminModeloMovilBean {
 @EJB
    private ModelomovilFacade modelomovilFacade;
    
    public List<Modelomovil> todosModelos;
    public Modelomovil model;
    public Modelomovil AEditar;
    public Modelomovil AAnadir;
    
    /**
     * Creates a new instance of AdminModeloMovilBean
     */
    public AdminModeloMovilBean() {
        this.AAnadir = new Modelomovil();
        this.AEditar = new Modelomovil();
    }

    public List<Modelomovil> getTodosModelos() {
        return todosModelos;
    }

    public void setTodosModelos(List<Modelomovil> todosModelos) {
        this.todosModelos = todosModelos;
    }

    public Modelomovil getModel() {
        return model;
    }

    public void setModel(Modelomovil model) {
        this.model = model;
    }

    public Modelomovil getAEditar() {
        return AEditar;
    }

    public void setAEditar(Modelomovil aEditar) {
        this.AEditar = aEditar;
    }

    public Modelomovil getAAnadir() {
        return AAnadir;
    }

    public void setAAnadir(Modelomovil AAnadir) {
        this.AAnadir = AAnadir;
    }
    
    @PostConstruct
    public void InicListaModelos()
    {
        this.todosModelos = modelomovilFacade.findAll();
        
    }
    
    public void eliminarModelo() throws IOException
    {
        modelomovilFacade.remove(this.model);
        InicListaModelos();
   //     FacesContext.getCurrentInstance().getExternalContext().redirect("adminModelos.jsf");
    }
    
    public String editarModelo()
    {
        return "editarModelos.jsf";
    } 
    
    public void actualizarModelo() throws IOException
    {
        AEditar = model;
        modelomovilFacade.edit(AEditar);
        AEditar = new Modelomovil();
        InicListaModelos();
        FacesContext.getCurrentInstance().getExternalContext().redirect("adminModelos.jsf");
    }
    
    public void crearModelo() throws IOException
    {
        modelomovilFacade.create(AAnadir);
        AAnadir = new Modelomovil();
        InicListaModelos();
        FacesContext.getCurrentInstance().getExternalContext().redirect("adminModelos.jsf");
    }
}

lythosJSF2/lythosJSF2-war/src/java/modelosFijos/adminModelosFijosBean.java
package modelosFijos;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

import dao.ModelofijoFacade;
import entidades.Modelofijo;
import java.io.IOException;
import java.util.Date;
import java.util.List;
import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import javax.faces.context.FacesContext;

/**
 *
 * @author ROOT
 */
@ManagedBean(name="adminModelosFijosBean")
@RequestScoped
public class adminModelosFijosBean {

    /**
     * Creates a new instance of adminModelosFijosBean
     */
    
    @EJB
    ModelofijoFacade modelofijofacade;
        
      
    private int idModelosFijos;
    private String detalles;
    private String imagen;
    private Date lanzamiento;
    private String marca;
    private String modelo;
    
    List<Modelofijo> todosmodelos;
    
    private Modelofijo modfijo;
    private Modelofijo aEditar;
    private Modelofijo selectedmodelofijo;
    
    private List<Modelofijo> filteredModeloFijo;
    
    @PostConstruct
    public void adminModelosFijosBean(){
       todosmodelos=(List<Modelofijo>) modelofijofacade.findAll();
       selectedmodelofijo  = new Modelofijo();
    }
    
    public List<Modelofijo> getModelos(){
       return todosmodelos;
    }
    
    public adminModelosFijosBean() {
        

    }

    public int getidModelosFijos() {
        return idModelosFijos;
    }

    public void setdModelosFijos(int idModelosFijos) {
        this.idModelosFijos = idModelosFijos;
    }
    
    
    
    public String getDetalles() {
        return detalles;
    }

    public void setDetalles(String detalles) {
        this.detalles = detalles;
    }

    public String getImagen() {
        return imagen;
    }

    public void setImagen(String imagen) {
        this.imagen = imagen;
    }

    public Date getLanzamiento() {
        return lanzamiento;
    }

    public void setLanzamiento(Date lanzamiento) {
        this.lanzamiento = lanzamiento;
    }

    public String getMarca() {
        return marca;
    }

    public void setMarca(String marca) {
        this.marca = marca;
    }

    public String getModelo() {
        return modelo;
    }

    public void setModelo(String modelo) {
        this.modelo = modelo;
    }

    public Modelofijo getSelectedmodelofijo() {
        return selectedmodelofijo;
    }

    public void setSelectedmodelofijo(Modelofijo selectedmodelofijo) {
        this.selectedmodelofijo = selectedmodelofijo;
    }
    
    public String goToEditar() throws IOException{
       return "editarModelosFijos.jsf";
       
      
   }

    public String editando(){
//        Modelofijo modelofijo = new Modelofijo();
//        modelofijo.setDetalles(detalles);
//        modelofijo.setImagen(imagen);
//        //modfijo.setLanzamiento(lanzamiento);
//        modelofijo.setMarca(marca);
//        modelofijo.setModelo(modelo);
        modelofijofacade.edit(this.selectedmodelofijo);
        todosmodelos=(List<Modelofijo>) modelofijofacade.findAll();
        return "adminModelosFijos.jsf";
        
               
    }
    
    
     public String editandoForm(){
       /*  this.setdModelosFijos(this.selectedmodelofijo.getIdModeloFijo());
         this.setDetalles(this.selectedmodelofijo.getDetalles());
         this.setImagen(this.selectedmodelofijo.getImagen());
         this.setMarca(this.selectedmodelofijo.getMarca());
         this.setModelo(this.selectedmodelofijo.getModelo());*/
         return "editarModelosFijos.jsf";
     }
     
      public List<Modelofijo> getFilteredModeloFijo() {  
        return filteredModeloFijo;  
    }  
  
    /**
     *
     * @param filteredMunicipios
     */
    public void setfilteredModeloFijo(List<Modelofijo> filteredModeloFijo) {  
        this.filteredModeloFijo = filteredModeloFijo;  
    } 
    
     
    
    public void insertando() throws IOException{
        Modelofijo modelofijo = new Modelofijo();
        modelofijo.setDetalles(detalles);
        modelofijo.setImagen(imagen);
        //modfijo.setLanzamiento(lanzamiento);
        modelofijo.setMarca(marca);
        modelofijo.setModelo(modelo);
        modelofijofacade.create(modelofijo);
        todosmodelos=(List<Modelofijo>) modelofijofacade.findAll();
        FacesContext.getCurrentInstance().getExternalContext().redirect("adminModelosFijos.jsf");
    }


    
    public void Delete(Modelofijo modelofijo){
        modelofijofacade.remove(modelofijo);
        todosmodelos=(List<Modelofijo>) modelofijofacade.findAll();
    }
}

lythosJSF2/lythosJSF2-war/web/forIndex/footerguest.xhtml
<html xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets">
    <h:head />
    
    <h:body>   LALALALALALALALALALALALAALALA   LALALALALALALALALALALALAALALA
    <footer>
        <div id="footer">
            <div class="container">
                <div class="row-fluid">
                    <div class="span4">
                       <!-- <h4><strong><center>Mapa del sitio</center></strong></h4><br />-->
                        <div id="list4">
                            <ul>
                                <li><a href="index.jsp">Inicio</a></li>
                                <li><a href="http://www.malaga.es/">La Diputacion</a></li>
                                <li><a href="contacto.jsp">Contacto</a></li>
                                <li><a href="servicios.jsp">Servicios</a></li>
                            </ul>
                        </div>

                    </div>
                    <div class="span4 meteor-footer">
                        <center> by Meteor Systems<br />
                        <a href="http://www.meteor.ameh.es"><img src="img/meteorlogo1.png" /></a></center>
                    </div>
                    <div class="span4">
                        <a href="http://www.malaga.es"> <img src="img/diputacion.gif" height="100" /></a>
                    </div>
                </div>
            </div>

        </div>    


         <!-- VENTANA DE LOGIN -->
                <div id="modalLogin" class="modal hide fade" tabindex="-1" role="dialog">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                        <h3>Iniciar Sesion</h3>
                    </div>
                    <div class="modal-body">
                      <center>
                       
                            <h:form>
                                <h:inputText class="input-block-levelt"  title="Nombre de usuario" required="required" value="#{apiLogin.nickname}" />
                                <br/>
                                <h:inputSecret  class="input-block-levelt" title="Tu contraseña" required="required" value="#{apiLogin.password}" />
                                <br/>
                                <h:commandButton class="btn btn-success" value="Iniciar Sesion"  action="#{apiLogin.loginUser()}" /> 
                          </h:form>
                          
                          
                          </center>     
                        </div> 

                            <div class="modal-footer">
                            Proyecto Lythos - 2013
                          </div>

                        </div>


    </footer>

    </h:body>
</html>

lythosJSF2/lythosJSF2-war/web/forIndex/headerguest.xhtml
<!-- 
    Document   : headerguest
    Created on : 28-mar-2013, 2:05:29
    Author     : IsmiKin
    Description:  Cabecera para la vista del invitado, sin loguear
-->


<html xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets">
    <h:head />
    
<!-- Importamos los css para que funcione el carousel -->
<link rel="stylesheet" href="css/pages/carousel.css" />
<link rel="stylesheet" href="css/pages/index.css" />

<!-- NAVBAR
    ================================================== -->
    <div class="navbar-wrapper">
      <!-- Wrap the .navbar in .container to center it within the absolutely positioned parent. -->
      <div class="container">

        <div class="navbar navbar-inverse">
          <div class="navbar-inner">
            <!-- Responsive Navbar Part 1: Button for triggering responsive navbar (not covered in tutorial). Include responsive CSS to utilize. -->
            <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="brand" href="index.jsp">Proyecto Lythos</a>
            <!-- Responsive Navbar Part 2: Place all navbar contents you want collapsed withing .navbar-collapse.collapse. -->
            <div class="nav-collapse collapse">
              <ul class="nav">
                <li class="active"><a href="index.jsp">Inicio</a></li>
                <li><a href="http://www.malaga.es">La Diputación</a></li>
                <li><a href="contacto.jsp">Contacto</a></li>
                <!-- Read about Bootstrap dropdowns at http://twitter.github.com/bootstrap/javascript.html#dropdowns -->
                <li class="dropdown">
                  <a href="servicios.jsp" class="dropdown-toggle" data-toggle="dropdown">Servicios <b class="caret"></b></a>
                  <ul class="dropdown-menu">
                      <li class="nav-header">Llamar</li>
                    <li><a href="servicios.jsp#Fija">Telefonía Fija</a></li>
                    <li><a href="servicios.jsp#Movil">Telefonía Movil</a></li>
                    <li class="divider"></li>
                    <li class="nav-header">Navegar</li>
                    <li><a href="servicios.jsp#Linea">Linea de Internet</a></li>
                    <li><a href="servicios.jsp#TDatos">Tarifa de Datos</a></li>                                        
                  </ul>
                </li>
              </ul>
                
                       <form class="navbar-form pull-right">                           
                           <button id="btnIniciar" type="submit" class="btn btn-success" data-toggle="modal" data-target="#modalLogin" value="Iniciar Sesion" >Iniciar Sesion</button>
                        </form>
              
                
                
            </div><!--/.nav-collapse -->
          </div><!-- /.navbar-inner -->
        </div><!-- /.navbar -->

      </div> <!-- /.container -->
    </div><!-- /.navbar-wrapper -->



    <!-- Carousel
    ================================================== -->
    <div id="myCarousel" class="carousel slide">
      <div class="carousel-inner">
        <div class="item active">
          <img src="img/slide01.png" alt="" />
          <div class="container">
            <div class="carousel-caption">
                
                    <h1 class="claro">Por y para Málaga.</h1>
                    <p class="lead claro">Todos nuestros servicios estan disponibles a todos los Municipios de la provincia de Málaga. Estamos aqui para ayudar a todos los malagueños.</p>
                    <a class="btn btn-large btn-primary" href="contacto.jsp">Contacta</a>
               
            </div>
          </div>
        </div>
        <div class="item">
          <img src="./img/slide02.png" alt="" />
          <div class="container">
            <div class="carousel-caption">
              <h1 class="claro">La última tecnología.</h1>
              <p class="lead claro">Queremos que Málaga sea una provincia líder y moderna y por ello ofrecemos las últimas novedades del mercado con una financiación más que competitiva.</p>
              <a class="btn btn-large btn-primary" href="servicios.jsp">Nuestros servicios</a>
            </div>
          </div>
        </div>
        <div class="item">
          <img src="./img/slide03.png" alt="" />
          <div class="container">
            <div class="carousel-caption">
              <h1>La Diputación.</h1>
              <p class="lead claro">La Diputación de Málaga es un organismo que esta por y para los malagueños. Ofrecemos diversos servicios y este mismo portal es una prueba de ella.</p>
              <a class="btn btn-large btn-primary" href="diputacion.jsp">La Diputación</a>
            </div>
          </div>
        </div>
      </div>
      <a class="left carousel-control" href="index.jsp#myCarousel" data-slide="prev">‹</a>
      <a class="right carousel-control" href="index.jsp#myCarousel" data-slide="next">›</a>
    </div><!-- /.carousel -->
        
    
</html>

lythosJSF2/lythosJSF2-war/web/forIndex/headerlibs.xhtml
<!--
    Document   : header
    Created on : 23-mar-2013, 19:08:35
    Author     : IsmiKin
-->


<!DOCTYPE html>

<html xmlns:h="http://java.sun.com/jsf/html">
    <h:head>
        
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <title>Proyecto Lythos</title>
        <link rel="stylesheet" href="css/kendoui/kendo.common.min.css" />
        <link rel="stylesheet" href="css/kendoui/kendo.default.min.css" />
        <link rel="stylesheet" href="css/bootstrap/bootstrap.min.css" />
        
        <link href='http://fonts.googleapis.com/css?family=Merienda:400,700' rel='stylesheet' type='text/css' />
        
        <script src="js/jquery.min.js"></script>
        <script src="js/kendo.all.min.js"></script>
       <!-- <script src="js/bootstrap.min.js"></script> -->
            
        <!-- BOOTSTRAP JS -->
        
        <script src="js/bootstrap-transition.js"></script>
        <script src="js/bootstrap-alert.js"></script>
        <script src="js/bootstrap-modal.js"></script>
        <script src="js/bootstrap-dropdown.js"></script>
        <script src="js/bootstrap-scrollspy.js"></script>
        <script src="js/bootstrap-tab.js"></script>
        <script src="js/bootstrap-tooltip.js"></script>
        <script src="js/bootstrap-popover.js"></script>
        <script src="js/bootstrap-button.js"></script>
        <script src="js/bootstrap-collapse.js"></script>
        <script src="js/bootstrap-carousel.js"></script>
        <script src="js/bootstrap-typeahead.js"></script>
                
        <link href="img/favicon.ico" rel="icon" type="image/x-icon" />
        
    </h:head>
</html>
    

lythosJSF2/lythosJSF2-war/web/index.jsp
<%-- 
    Document   : index
    Created on : 02-jun-2013, 20:05:52
    Author     : IsmiKinPorti
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>JSP Page</title>
    </head>
    <body>
        <h1>Hello World!</h1>
    </body>
</html>

lythosJSF2/lythosJSF2-war/web/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        Hello from Facelets
        <br />
        <h:link outcome="welcomePrimefaces" value="Primefaces welcome page" />
    </h:body>
</html>

lythosJSF2/lythosJSF2-war/web/jsf/home/errorLogin.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      >
    <h:head>
        <title>Lythos - Error Login</title>
    </h:head>
    <h:body>
        
            
   <ui:include src="../../shared/headerlibs.xhtml" />
   <ui:include src="../../shared/headerguest.xhtml" />
   
        <script src="js/pages/index.js"></script>

            <div id="wrap">

                <div class="row  info-index">

                    <div  class="span12">
                        <center><p class="text-center welcome-title"><h1>¡Ups! Parece que ha ocurrido un error</h1></p></center>
                    </div>

                        <div class="row-fluid">

                            <div class="span4">
                                <img class="img-rounded" src="img/dead_smile.png" /> >
                            </div>


                            <div class="span8 textospan">
                                <strong>¡Ha habido un problema al entrar en la plataforma  !</strong><br /><br />
                               Pruebe a escribir de nuevo su cuenta de usuario y contraseña      <br /><br />


                               <form id="loginForm" action="login" method="POST">
                                    <input type="text" id="user" name="nickname" class="input-block-levelt" placeholder="Nombre de Usuario" title="Nombre de usuario" required="required"
                                           />
                                    <br />
                                    <input id="pass" name="pass" type="password" class="input-block-levelt" placeholder="Contraseña" title="Tu contraseña" required="required" />
                                    <br />
                                    <button id="btnIniciarSesion" type="submit" class="btn btn-success" >Iniciar Sesion</button>
                               </form>

                               <ul>
                                   <li>Si tienes un <b>problema tecnico</b> ponte en contacto con nosotros a través de la Oficina de Soporte Técnico o envienos un correo
                                        <a href="contacto.jsp" class="btn btn-warning">Contactar</a>
                                   </li>                       

                               </ul>

                            </div>

                        </div>

                    </div>

            </div>
        
        <ui:include src="../../shared/footerguest.xhtml" />
    </h:body>
</html>

lythosJSF2/lythosJSF2-war/web/jsf/home/home.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      >
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        
          
   <ui:include src="../../shared/headerlibs.xhtml" />
   <ui:include src="../../shared/headeradmin.xhtml" />
        
   
    <div class="content-main row-fluid">
            <div class="span8 column">
        
        
     </div><!--  END CENTER CONTENT -->

        <ui:include src="../../shared/menuRightAdmin.xhtml" />        

    </div> <!-- END content-main row-fluid -->
                
    </h:body>
    
    <ui:include src="../../shared/footerguest.xhtml" />
</html>

lythosJSF2/lythosJSF2-war/web/jsf/home/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:c="http://java.sun.com/jsp/jstl/core"
      xmlns:ui="http://java.sun.com/jsf/facelets">
    <h:head>
        <title>Lythos Inicio</title>
    </h:head>
    <h:body>
        
   <ui:include src="../../forIndex/headerlibs.xhtml" />
   <ui:include src="../../forIndex/headerguest.xhtml" />
        
    <script src="js/pages/index.js"></script>

    <h:form rendered="#{not empty Logeando.username}">
    <h:commandLink value="Logout" action="#{auth.logout}" />
    </h:form>
    <h:link value="Login" outcome="login" rendered="#{empty Logeando.username}" />
    
    <div id="wrap">

        <div class="row  info-index">
              
            <div  class="span12">
                <center><p class="text-center welcome-title"><h1>¡Bienvenido!</h1></p></center>
            </div>

                <div class="row-fluid">

                    <div class="span4">
                        <img class="img-rounded" src="img/business-people-2_s.png" /> 
                    </div>


                    <div class="span8 textospan">
                        <strong>¡Bienvenido al Proyecto !</strong><br /><br />
                       A través de esta plataforma podra organizar y ver sus facturas.       <br /><br />

                       <ul>
                           <li>Si tienes un <b>problema tecnico</b> ponte en contacto con nosotros a través de la Oficina de Soporte Técnico o envienos un correo
                                <a href="contacto.jsp" class="btn btn-warning">Contactar</a>
                           </li>
                           <li> 
                               Si aun no tienes plan contratado con nosotros te invitamos a que te pases por nuestros servicios
                               <a href="servicios.jsp" class="btn btn-info">Servicios</a>
                           </li>
                           <li>
                               Si ya disfrutas de nuestros Servicios, ¡Inicia Sesion!
                               <a href="servicios.jsp" class="btn btn-success">Iniciar Sesion</a>
                           </li>

                       </ul>

                    </div>

                </div>

            </div>

        </div>
    </h:body>
    
    <ui:include src="../../forIndex/footerguest.xhtml" />
</html>

lythosJSF2/lythosJSF2-war/web/jsf/home/index2.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:c="http://java.sun.com/jsp/jstl/core"
      xmlns:ui="http://java.sun.com/jsf/facelets">
    <h:head>
        <title>Lythos Inicio</title>
    </h:head>
    <h:body>
        
   <ui:include src="../../shared/headerlibs.xhtml" />
   <ui:include src="../../shared/headerguest.xhtml" />
        
    <script src="../../js/pages/index.js"></script>

    <h:form rendered="#{not empty Logeando.username}">
    <h:commandLink value="Logout" action="#{auth.logout}" />
    </h:form>
    <h:link value="Login" outcome="login" rendered="#{empty Logeando.username}" />
    
    <div id="wrap">

        <div class="row  info-index">
              
            <div  class="span12">
                <center><p class="text-center welcome-title"><h1>¡Bienvenido!</h1></p></center>
            </div>

                <div class="row-fluid">

                    <div class="span4">
                        <img class="img-rounded" src="img/business-people-2_s.png" /> 
                    </div>


                    <div class="span8 textospan">
                        <strong>¡Bienvenido al Proyecto !</strong><br /><br />
                       A través de esta plataforma podra organizar y ver sus facturas.       <br /><br />

                       <ul>
                           <li>Si tienes un <b>problema tecnico</b> ponte en contacto con nosotros a través de la Oficina de Soporte Técnico o envienos un correo
                                <a href="contacto.jsp" class="btn btn-warning">Contactar</a>
                           </li>
                           <li> 
                               Si aun no tienes plan contratado con nosotros te invitamos a que te pases por nuestros servicios
                               <a href="servicios.jsp" class="btn btn-info">Servicios</a>
                           </li>
                           <li>
                               Si ya disfrutas de nuestros Servicios, ¡Inicia Sesion!
                               <a href="servicios.jsp" class="btn btn-success">Iniciar Sesion</a>
                           </li>

                       </ul>

                    </div>

                </div>

            </div>

        </div>
    </h:body>
    
    <ui:include src="../../shared/footerguest.xhtml" />
</html>

lythosJSF2/lythosJSF2-war/web/jsf/modelosFijos/adminModelosFijos.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets">
    <h:head>
        
        
        <title>Modelos Fijos</title>
        
    </h:head>
    <h:body>
        
   <ui:include src="../../shared/headerlibs.xhtml" />
   <ui:include src="../../shared/headeradmin.xhtml" />
        
   
    <div class="content-main row-fluid">
            <div class="span8 column">
  
        
        
        
        
        <h:form>
            <h:dataTable var="modelosFijos" value="#{adminModelosFijosBean.modelos}" class="admin-table table table-hover">
                <h:column>
                    <f:facet name="header"> idModelosFijos </f:facet>
                   #{modelosFijos.idModeloFijo}
                </h:column>
                <h:column>
                    <f:facet name="header"> Detalles </f:facet>
                    #{modelosFijos.detalles}
                </h:column>
                <h:column>
                    <f:facet name="header"> Imagen </f:facet>
                    #{modelosFijos.imagen}
                </h:column>
                <h:column>
                    <f:facet name="header"> Lanzamiento </f:facet>
                    #{modelosFijos.lanzamiento}
                </h:column>
                <h:column>
                    <f:facet name="header"> Marca </f:facet>
                    #{modelosFijos.marca}
                </h:column>
                <h:column>
                    <f:facet name="header"> Modelo </f:facet>
                    #{modelosFijos.modelo}
                </h:column>
                <h:column>
                          <f:facet name="header"> Acciones  <h:commandButton class="btn btn-info" action="insertarModelosFijos.jsf" value="Insert" /></f:facet>
                    <h:commandButton class="btn btn-danger" action="#{adminModelosFijosBean.Delete(modelosFijos)}" 
                                     value="Delete">
                        <f:ajax render="@form" />
                    </h:commandButton>
                                                                                    
                    
                          <h:commandButton class="btn btn-warning" value="Editar"  action="#{adminModelosFijosBean.editandoForm()}" > 
                          <f:setPropertyActionListener value="#{modelosFijos}"
                                                        
                                                       target="#{adminModelosFijosBean.selectedmodelofijo}"  />
                      </h:commandButton>

                </h:column>
                
                
                
            </h:dataTable>
            <center>
            
                
            <!-- <h:commandButton action="#{modelosFijos.cancel}" value="Cancel">
                    <f:setPropertyActionListener value="#{modelosFijos}"
                                                 target="#{modelosFijos.selectedModelo}"/>
             </h:commandButton>   -->
                
            </center>
        </h:form>
                
                
                
          <!-- FIN CONTENIDO DE LA PAGINA -->
            
            
         </div><!--  END CENTER CONTENT -->

        <ui:include src="../../shared/menuRightAdmin.xhtml" />        

    </div> <!-- END content-main row-fluid -->
        
    </h:body>
    
    <ui:include src="../../shared/footerguest.xhtml" />
</html>